### ISSUE TITLE
Correctly Calculate Icon & Label in PieSlice

### ISSUE THREAD

**Issue by felixrieseberg** [CatalystCode/radial-menu#11]
The way I currently calculate the [correct position for the icon and its label](https://github.com/CatalystCode/radial-menu/blob/master/RadialMenuControl/UserControl/PieSlice.xaml.cs#L183-L185) is horrible and needs to be fixed.

**Comment by ritazh** [comment]
I think I got this to work now. :)

**Comment by ritazh** [comment]
Fixed by #23
