### ISSUE TITLE
PieSlice memory leak

### ISSUE THREAD

**Issue by nikz-codes** [CatalystCode/radial-menu#132]
PieSlice objects leak because of event handlers attached at https://github.com/CatalystCode/radial-menu/blob/6698d256fc96afdcab7c8c93bd76fca9698dcd41/RadialMenuControl/UserControl/Pie.xaml.cs#L225-L228. These handlers are never detached. Subsequent Draw() calls create new PieSlice objects and attach new event handlers.

**Comment by felixrieseberg** [comment]
Wow, great catch, thank for very much! Would you at all be interested in sending us a PR?
