### ISSUE TITLE
Enable Radio-Style/Toggle-Style Selection

### ISSUE THREAD

**Issue by felixrieseberg** [CatalystCode/radial-menu#15]
If used for a tool-selection, the radial menu should support radio-style selection of pie slices. Right now, all pie slices are simple buttons - for a radio-style selection, we need a "selectedSlice" and also need to indicate if a slice has been selected.

Also, this whole thing should be configurable. Buttons should be able to belong to a Radio-Group, or be individual Toggle-Buttons.

**Comment by ritazh** [comment]
Closed by #31
