### ISSUE TITLE
Z-Order is broken

### ISSUE THREAD

**Issue by felixrieseberg** [CatalystCode/radial-menu#20]
http://blogs.u2u.be/diederik/post/2014/02/23/A-Floating-Control-for-Windows-8-Store-apps.aspx

**Comment by ritazh** [comment]
@felixrieseberg Is this related to the z-order we talked about the other day? I think I got it to work now.

**Comment by felixrieseberg** [comment]
That'd be awesome. Even if not, I'd love a sane PR. If you want to check if this issue will remain relevant, give the test app a background color. If the control disappears, we still need to fix it.

Don't let that hold you back on the icon/label position thing though!

**Comment by felixrieseberg** [comment]
This is now fixed.
