### ISSUE TITLE
Meter Sub-Menu

### ISSUE THREAD

**Issue by sedouard** [CatalystCode/radial-menu#28]
<img width="268" alt="screen shot 2015-09-29 at 10 15 22 pm" src="https://cloud.githubusercontent.com/assets/3053263/10182920/2c3aef7c-66f8-11e5-9765-f862ec8bbf64.png">

**Comment by sedouard** [comment]
@felixrieseberg @ritazh how does this look to you guys?
![](http://recordit.co/xJqawIzXn8/gif/notify)

**Comment by felixrieseberg** [comment]
Looks awesome! I think that should be merged as is, but out of curiosity: Could we (or the user) increase the inner dial radius?

**Comment by sedouard** [comment]
Yeah all that stuff is exposed

**Comment by sedouard** [comment]
PR coming right up!

**Comment by ritazh** [comment]
Sweet!

**Comment by felixrieseberg** [comment]
I'll close this, since we do have the meter - but I'll write up an issue for the "advanced" meter submenu.
