### ISSUE TITLE
Submenu: Meter with variable increments

### ISSUE THREAD

**Issue by felixrieseberg** [CatalystCode/radial-menu#40]
We already have a working meter submenu, but the increments are currently fixed. In order for the submenu to be usable for things like font size selectors, we'll need varying increments. This can probably be best achieved by dividing the circle up into sections and assigning step intervals to each section. Dividing the circle up into for example four slices, the user should be able to define a submenu with the following markers:

000° - 0
090° - 12
180° - 36
270° - 72

**Comment by sedouard** [comment]
closed via https://github.com/CatalystCode/radial-menu/pull/55
