### ISSUE TITLE
Center Button jumps to incorrect position

### ISSUE THREAD

**Issue by felixrieseberg** [CatalystCode/radial-menu#47]
If the menu is too close to the right/bottom border of its movement area, it'll jump to an incorrect location when opening/closing the button.

**Comment by felixrieseberg** [comment]
Actually, the thing now jumps to position now matter what. I think this happened with #45 - @sedouard, can you take a look?

**Comment by sedouard** [comment]
sure i'll take a peek

**Comment by sedouard** [comment]
@felixrieseberg https://github.com/CatalystCode/radial-menu/pull/50 helps but the weirdness on the borders still persists.

**Comment by felixrieseberg** [comment]
@sedouard Thanks! I got my issue fixed now, too - so we're good here :+1:
