### ISSUE TITLE
Setting SelectedValue/LockedValue on MeterSubMenu does not update UI

### ISSUE THREAD

**Issue by PierceDrawboard** [CatalystCode/radial-menu#73]

**Comment by PierceDrawboard** [comment]
Need a way of updating value from code. Either setting LockedValue to previously selected value on load event, or using Binding to LockedValue.

**Comment by sedouard** [comment]
@PierceDrawboard  https://github.com/CatalystCode/radial-menu/pull/87 should fix this.
