### ISSUE TITLE
Possible to add bindings to MeterSubMenu? 

### ISSUE THREAD

**Issue by PierceDrawboard** [CatalystCode/radial-menu#76]
Is it possible to add binding support for MeterSubMenu LockedValue, and any state based info that might need to be bound to view model data. I.e. custom stroke width textbox etc..

**Comment by sedouard** [comment]
Sure thing, I'll make dependency properties for all of these. including for `LockedValue`

**Comment by sedouard** [comment]
Hey @PierceDrawboard! Can you try out the latest MeterSubMenu and let me know this works? https://github.com/CatalystCode/radial-menu/pull/87

**Comment by PierceDrawboard** [comment]
Doesn't seem to be. It is "LockedValue" that is actually displayed?

**Comment by felixrieseberg** [comment]
Aaaaaand done :rainbow:
