### ISSUE TITLE
Expand glyph blocks OuterArcPressed. Needs to be not hit test visible.

### ISSUE THREAD

**Issue by PierceDrawboard** [CatalystCode/radial-menu#92]

**Comment by felixrieseberg** [comment]
Can you expand on this a little bit? I just want to make sure I understand this correctly...

**Comment by felixrieseberg** [comment]
Never mind, found it. Rita will be yelled at momentarily.

**Comment by PierceDrawboard** [comment]
When you click or mouse-over directly on the little white triangle for the submenu the events are blocked from outer arc. So no mouseover effect and no click event.

**Comment by PierceDrawboard** [comment]
Haha! Sorry Rita!

**Comment by felixrieseberg** [comment]
Already fixed :)
